[package]
name = "ocean"
version = "0.1.0"
authors = ["Michael Coblenz <mcoblenz@ucsd.edu>", "Dylan Lukes <dlukes@ucsd.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"